version: '3.8'

services:
  airastana-db:
    image: postgres:latest
    container_name: airastana-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - app-network

  auth-service:
    build:
      context: ../auth-service/
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      DATASOURCE_URL: jdbc:postgresql://airastana-db:5432/auth_service_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: 123
    depends_on:
      - airastana-db
    networks:
      - app-network

  flight-service:
    build:
      context: ../flight-service/
      dockerfile: Dockerfile
    container_name: flight-service
    environment:
      DATASOURCE_URL: jdbc:postgresql://airastana-db:5432/flight_service_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: 123
    depends_on:
      - airastana-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: